[FIXED] Correct input for "parse 0" test case
nats-io/nats.go pull request #1334
Opened 2023-06-23 14:19 UTC by YukiBobier

# Resolve issue #1333

This change aligns the input with the name of the test case and ensures that the function is accurately tested with this input.

2023-06-23 14:37 UTC, piotrpio requested changes
Hey @YukiBobier , thanks for the PR, indeed this may have been confusing.

Just one thing - I think we should still have a test where the input is an empty string, just with better test case name ("parse empty string"). That would mean that we should have 2 test cases instead of 1 - one with "0" as input and other with "" as input.

2023-06-23 15:53 UTC, YukiBobier commented
> Hey @YukiBobier , thanks for the PR, indeed this may have been confusing.
> 
> Just one thing - I think we should still have a test where the input is an empty string, just with better test case name ("parse empty string"). That would mean that we should have 2 test cases instead of 1 - one with "0" as input and other with "" as input.

Hi @piotrpio ,

Thanks for your feedback on this pull request.

I wanted to point out that there is already an existing test case that tests the function with an empty string as input. Here's the test case:
https://github.com/nats-io/nats.go/blob/7c2bded3d4788650393b681c5df4a1bf8553bd15/internal/parser/parse_test.go#L46-L50

Given this, I've made the change to have the "parse 0" test case use the string "0" as input, as per the test case name.

If there's any misunderstanding on my part, please let me know.

2023-06-23 17:34 UTC, piotrpio approved these changes
@YukiBobier My bad, I missed that there was a test case for empty string already.

LGTM, thanks for cotribution!

2023-06-23 17:35 UTC, merged

2023-06-24 14:09 UTC, YukiBobier commented
@piotrpio No problem at all! I'm glad the changes look good to you. Thanks for your approval and for taking the time to review my pull request.

I'm really happy to contribute to this project and look forward to making further contributions.