[ADDED] ObjectStore API in jetstream package
nats-io/nats.go pull request #1450
Opened 2023-10-27 13:45 UTC by piotrpio

This PR adds ObjectStore API to `jetstream` package.

It is for the most part a port of `object.go` and `object_test.go` to the new package, without many changes. All object store tests moved from `nats` package pass in the new package (after adding context and changing structs packages)

Notable changes:
- All interfaces and structs ported to `jetstream` package
- `Put()` and `Watch()` methods use the legacy push consumers to prevent permission issues when moving to new API
- API now utilises `context.Context` extensively in line with the rest of the package
- Usage of typed errors

Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

2023-12-11 11:13 UTC, Jarema requested changes
Generally looks good and playes nicely with the new `jetstream` package.
There are few things to adresss.

2023-12-11 11:13 UTC, Jarema commented on jetstream/object.go
> +	go func() {
We probably should cancel the goroutine in case of `ctx.Done`.

2023-12-12 10:57 UTC, piotrpio commented on jetstream/object.go
> +	objNoPending        = "0"
It's a "0", so this means "no pending"

2023-12-15 08:58 UTC, Jarema approved these changes
LGTM!

2024-01-12 09:57 UTC, Jarema approved these changes
LGTM!

2024-01-12 10:07 UTC, merged