Add KeysWithFilter & ListKeysWithFilters methods to KV interface
nats-io/nats.go pull request #1658
Opened 2024-06-20 15:58 UTC by Darshan174

implemented a method KeysWithFilters to return keys matching specified filters and ListKeysWithFilters to provide an iterable list of keys (as suggested). And additionally defined KeyIterator for iterating over keys and a utility function matchesFilters to check if a key meets all filter criteria.

2024-06-20 15:58 UTC, Darshan174 commented
Closes #1655

2024-06-21 07:12 UTC, Jarema requested changes
Hey!

Thanks for your effort.
However, this PR needs quite some work, as it does not do what it should do.

Please take a look at `Keys` or `ListKeys` to see how we are using `ordered consumer` to fetch the keys from the server.

Also, this is where they should be filtered out - by providing `subject filters` with appropriate subjects.

2024-06-21 07:12 UTC, Jarema commented on jetstream/kv.go
> +func (js *jetStream) KeysWithFilters(filter []string) ([]string, error) {
Filtering the keys does not mean filtering them on client side code.
It means passing `subject filters` to `ordered consumer`. Take a look how `ListKeys` or `Keys` are implemented.

2024-06-21 07:12 UTC, Jarema commented on jetstream/kv.go
> +// NewKeyIterator creates a new KeyIterator.
To see how those APIs should work in nats.go client, please take a look at `ListKeys` method.

2024-06-21 15:24 UTC, Darshan174 commented
> Hey!
> 
> Thanks for your effort. However, this PR needs quite some work, as it does not do what it should do.
> 
> Please take a look at `Keys` or `ListKeys` to see how we are using `ordered consumer` to fetch the keys from the server.
> 
> Also, this is where they should be filtered out - by providing `subject filters` with appropriate subjects.

Hey @Jarema! Thank you for your patience in guiding me. I'm having a hard time figuring out the `subject filters` which u suggested. Could you please provide more details on this?

2024-06-22 07:36 UTC, Darshan174 commented
Hey @Jarema! Thank you for your patience in guiding me. I've read through the [docs](https://docs.nats.io/nats-concepts/jetstream/streams#subjects) about FIlterSubject (I hope this is what you were referring to), but I'd a hard time understanding the implimentation of passing subject filters to ordered customers in ListKeys from the Kv.go file. Could you please provide more details on this?

2024-06-26 10:35 UTC, closed without merging