[ADDED] CleanupPublisher method for removing internal JetStream subscription
nats-io/nats.go pull request #1690
Opened 2024-07-31 13:30 UTC by piotrpio

Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

2024-07-31 13:36 UTC, wallyqs commented on js.go
> +	// All pending async publishes will fail with ErrJetStreamContextClosed.
```suggestion
	// All pending async publishes will fail with ErrJetStreamPublisherClosed.
```

2024-08-08 08:17 UTC, Jarema requested changes
Looks ok.  Some questions added.

2024-08-08 08:17 UTC, Jarema commented on jetstream/jetstream.go
> +			errCb(js, paf.msg, ErrJetStreamPublisherClosed)
is it safe to unlock and lock again?

2024-08-08 08:17 UTC, Jarema commented on js.go
> +			errCb(js, paf.msg, ErrJetStreamPublisherClosed)
same here.

2024-08-09 08:00 UTC, Jarema approved these changes
LGTM!

2024-08-12 07:33 UTC, merged