[ADDED] UserInfoHandler for dynamically setting user/password
nats-io/nats.go pull request #1713
Opened 2024-09-10 21:12 UTC by piotrpio

Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

2024-09-11 08:34 UTC, Jarema requested changes
Looks ok, but I don't think it's a good name.

2024-09-11 08:34 UTC, Jarema commented on nats.go
> +func UserInfoHandler(cb UserInfoCB) Option {
the name `UserInfo` is a bit ambigous. 
Maybe something hinting it's about Username and password being set?

2024-09-19 13:21 UTC, tommyjcarpenter commented on nats.go
> +		if nc.Opts.UserInfo != nil {
...this tiny change will have huge opportunities for our organization (from #1694)!

2024-09-20 08:44 UTC, Jarema commented on nats.go
> +func UserInfoHandler(cb UserInfoCB) Option {
Ok, understood that its done for consistency.

2024-09-20 08:45 UTC, Jarema approved these changes
LGTM

2024-09-20 09:17 UTC, merged

2024-09-20 11:46 UTC, tommyjcarpenter commented
Is there a setter for this like some of the other CBs?