Fix auth revoke err not being invoked in async error handler
nats-io/nats.go pull request #684
Opened 2021-03-24 23:27 UTC by wallyqs

2021-03-24 23:30 UTC, kozlovic requested changes

2021-03-24 23:30 UTC, kozlovic commented on nats.go
> +	if strings.HasPrefix(e, `User Authentication Revoked`) {
Make this a constant and all lower case. We convert the content of error string to lower (see line 2773)

2021-03-24 23:30 UTC, kozlovic commented on nats.go
> +	if strings.HasPrefix(e, `User Authentication Revoked`) {
(add after `AUTHENTICATION_EXPIRED_ERR` const)

2021-03-25 00:05 UTC, matthiashanel commented
@kozlovic just for completeness. this will change how that error is surfaced. (for the better, but it's a change)
without this we'd invoke DisconnectErrHandler without error. The revoked error then could be found in nc.LastError()
```go
nats.DisconnectErrHandler(func(nc *nats.Conn, err error) {
	log.Printf("Disconnected due to: %s, will attempt reconnect", err, nc.LastError())
}),
```

With this change the error handler is invoked separately
```
19:46:00 Unexpected NATS error: nats: authentication revoked <--- ErrorHandler
19:46:00 Disconnected due to: EOF, will attempt reconnect <---- DisconnectErrHandler
19:46:02 Unexpected NATS error: nats: authorization violation <--- ErrorHandler
19:46:04 Unexpected NATS error: nats: authorization violation <--- ErrorHandler
```

2021-03-25 00:38 UTC, matthiashanel reviewed
I concur with Ivan.

2021-03-25 14:42 UTC, kozlovic approved these changes
LGTM, and good to have added a test!

2021-03-25 15:38 UTC, merged