js: make js.Subscribe context aware
nats-io/nats.go pull request #872
Opened 2021-12-14 18:06 UTC by wallyqs

Can now attach a context to a subscription so that it is unsubscribed and/or consumer deleted via propagation of cancellation via parent context.  This helps specially with `kv.Watch` functions that have an ordered consumer subscription.

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

2021-12-14 18:13 UTC, ripienaar commented
Nice, I am not that concerned to make this work for kv atm though your change is small enough there.

For kv we must not accept WatchOpts on various places where its accepted now - we need to add a new kind of opt like CancelOpt that only accepts `nats.Context()` since that the only valid option for `Keys()` for example.  I can take care of that once the basic cancelable subscribe and order consumer is in place

2021-12-14 18:18 UTC, kozlovic requested changes

2021-12-14 18:18 UTC, kozlovic commented on js.go
> +	// Wait for context to get canceled if there is one.
You should move this block at the end of the function, on success. You will note that at around line 1530 (or 1505 of original code), the subscription may be recreated.

2021-12-14 21:21 UTC, kozlovic approved these changes
LGTM

2021-12-14 22:02 UTC, merged

2021-12-24 10:39 UTC, tpihl commented
Will this work as a cancel more messages or will it delete a durable subscriber created in the subscribe call with WithDurable?

2021-12-24 18:10 UTC, wallyqs commented
If the app auto-created the durable (that is, without using `AddConsumer`) then the durable subscriber will be deleted when the context is canceled as well.