[FIXED] KV use of JS prefix
nats-io/nats.go pull request #910
Opened 2022-02-15 21:08 UTC by kozlovic

If the user creates a JS context with a custom prefix, this needs
to be used for the subject of the Put() and Delete() operations.
This is addressing the architecture design ADR-19.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

2022-02-15 21:23 UTC, wallyqs approved these changes
LGTM

2022-02-15 23:16 UTC, matthiashanel requested changes
Update is missing

I checked all locations of `b.WriteString(kv.pre)`.

PurgeDeletes uses it but goes through the js api, hence does not count. (as js uses the prefix) 
Same applies to Watch.

2022-02-15 23:18 UTC, matthiashanel approved these changes
Never Mind, update also goes through js.
LGTM

2022-02-15 23:35 UTC, kozlovic commented
@matthiashanel Actually, you were right. Adding the test showed that the update would fail, so we need to use the prefix there too. I added the test for that.

2022-02-16 00:03 UTC, matthiashanel approved these changes
LGTM

2022-02-16 00:06 UTC, merged